name = "onedrive"
type = "webpack"
workers_dev = true
account_id = "6ff5702fa965de82ac237a6e21ffdc09"
zone_id = "abb526ebd4bc7146dbc5fa173494aea3"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "6684bedd40a747148d9a6f2b28be3d9b", id = "6684bedd40a747148d9a6f2b28be3d9b" }
]

[env.staging]
name = "onedrive-staging"
