name = "sharepoint"
type = "webpack"
workers_dev = true
account_id = "d4e8f9c5850cf6c4fa611669fb3c2c38"
zone_id = "gdrivead.workers.dev"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "6684bedd40a747148d9a6f2b28be3d9b", id = "6684bedd40a747148d9a6f2b28be3d9b" }
]

[env.staging]
name = "onedrive-staging"
